### ISSUE TITLE
Cannot access github.gatech.edu

### ISSUE THREAD

**Issue by Marcus-Zhu** [ivalab/simData_imgSaver#1]
README.md instructed me to clone two repos from github.gatech.edu, which prompts for the LDAP credentials that I don't have access to. Are the repos the same as the github ones? I'm a little confused by the inconsistency of name: the github repo `simData` and the one in readme `simData_v2`.

**Comment by fujenchu** [comment]
Hi Marcus-Zhu,

Thanks for pointing it out. The links were not updated when we renamed/relocated the repositories. The readme file is updated now. Please let me know if you have any further questions.

Best,
Fu-Jen

**Comment by Marcus-Zhu** [comment]
Thanks!
